export const BRAND_ADMIN_LIST_REQUEST = "BRAND_ADMIN_LIST_REQUEST";
export const BRAND_ADMIN_LIST_SUCCESS = "BRAND_ADMIN_LIST_SUCCESS";
export const BRAND_ADMIN_LIST_FAIL = "BRAND_ADMIN_LIST_FAIL";
export const BRAND_ADMIN_LIST_RESET = "BRAND_ADMIN_LIST_RESET";

export const BRAND_ADMIN_CREATE_REQUEST = "BRAND_ADMIN_CREATE_REQUEST";
export const BRAND_ADMIN_CREATE_SUCCESS = "BRAND_ADMIN_CREATE_SUCCESS";
export const BRAND_ADMIN_CREATE_FAIL = "BRAND_ADMIN_CREATE_FAIL";
export const BRAND_ADMIN_CREATE_RESET = "BRAND_ADMIN_CREATE_RESET";

export const BRAND_ADMIN_UPDATE_REQUEST = "BRAND_ADMIN_UPDATE_REQUEST";
export const BRAND_ADMIN_UPDATE_SUCCESS = "BRAND_ADMIN_UPDATE_SUCCESS";
export const BRAND_ADMIN_UPDATE_FAIL = "BRAND_ADMIN_UPDATE_FAIL";
export const BRAND_ADMIN_UPDATE_RESET = "BRAND_ADMIN_UPDATE_RESET";

export const BRAND_ADMIN_DETAILS_REQUEST = "BRAND_ADMIN_DETAILS_REQUEST";
export const BRAND_ADMIN_DETAILS_SUCCESS = "BRAND_ADMIN_DETAILS_SUCCESS";
export const BRAND_ADMIN_DETAILS_FAIL = "BRAND_ADMIN_DETAILS_FAIL";
export const BRAND_ADMIN_DETAILS_RESET = "BRAND_ADMIN_DETAILS_RESET";

export const BRAND_ADMIN_DELETE_REQUEST = "BRAND_ADMIN_DELETE_REQUEST";
export const BRAND_ADMIN_DELETE_SUCCESS = "BRAND_ADMIN_DELETE_SUCCESS";
export const BRAND_ADMIN_DELETE_FAIL = "BRAND_ADMIN_DELETE_FAIL";
export const BRAND_ADMIN_DELETE_RESET = "BRAND_ADMIN_DELETE_RESET";

export const BRAND_LIST_REQUEST = "BRAND_LIST_REQUEST";
export const BRAND_LIST_SUCCESS = "BRAND_LIST_SUCCESS";
export const BRAND_LIST_FAIL = "BRAND_LIST_FAIL";
export const BRAND_LIST_RESET = "BRAND_LIST_RESET";
