export const CATEGORY_ADMIN_LIST_REQUEST = "CATEGORY_ADMIN_LIST_REQUEST";
export const CATEGORY_ADMIN_LIST_SUCCESS = "CATEGORY_ADMIN_LIST_SUCCESS";
export const CATEGORY_ADMIN_LIST_FAIL = "CATEGORY_ADMIN_LIST_FAIL";
export const CATEGORY_ADMIN_LIST_RESET = "CATEGORY_ADMIN_LIST_RESET";

export const CATEGORY_ADMIN_CREATE_REQUEST = "CATEGORY_ADMIN_CREATE_REQUEST";
export const CATEGORY_ADMIN_CREATE_SUCCESS = "CATEGORY_ADMIN_CREATE_SUCCESS";
export const CATEGORY_ADMIN_CREATE_FAIL = "CATEGORY_ADMIN_CREATE_FAIL";
export const CATEGORY_ADMIN_CREATE_RESET = "CATEGORY_ADMIN_CREATE_RESET";

export const CATEGORY_ADMIN_UPDATE_REQUEST = "CATEGORY_ADMIN_UPDATE_REQUEST";
export const CATEGORY_ADMIN_UPDATE_SUCCESS = "CATEGORY_ADMIN_UPDATE_SUCCESS";
export const CATEGORY_ADMIN_UPDATE_FAIL = "CATEGORY_ADMIN_UPDATE_FAIL";
export const CATEGORY_ADMIN_UPDATE_RESET = "CATEGORY_ADMIN_UPDATE_RESET";

export const CATEGORY_ADMIN_DETAILS_REQUEST = "CATEGORY_ADMIN_DETAILS_REQUEST";
export const CATEGORY_ADMIN_DETAILS_SUCCESS = "CATEGORY_ADMIN_DETAILS_SUCCESS";
export const CATEGORY_ADMIN_DETAILS_FAIL = "CATEGORY_ADMIN_DETAILS_FAIL";
export const CATEGORY_ADMIN_DETAILS_RESET = "CATEGORY_ADMIN_DETAILS_RESET";

export const CATEGORY_ADMIN_DELETE_REQUEST = "CATEGORY_ADMIN_DELETE_REQUEST";
export const CATEGORY_ADMIN_DELETE_SUCCESS = "CATEGORY_ADMIN_DELETE_SUCCESS";
export const CATEGORY_ADMIN_DELETE_FAIL = "CATEGORY_ADMIN_DELETE_FAIL";
export const CATEGORY_ADMIN_DELETE_RESET = "CATEGORY_ADMIN_DELETE_RESET";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
export const CATEGORY_LIST_RESET = "CATEGORY_LIST_RESET";
