export const DEVELOPMENT_ADMIN_LIST_REQUEST = "DEVELOPMENT_ADMIN_LIST_REQUEST";
export const DEVELOPMENT_ADMIN_LIST_SUCCESS = "DEVELOPMENT_ADMIN_LIST_SUCCESS";
export const DEVELOPMENT_ADMIN_LIST_FAIL = "DEVELOPMENT_ADMIN_LIST_FAIL";
export const DEVELOPMENT_ADMIN_LIST_RESET = "DEVELOPMENT_ADMIN_LIST_RESET";

export const DEVELOPMENT_ADMIN_CREATE_REQUEST =
  "DEVELOPMENT_ADMIN_CREATE_REQUEST";
export const DEVELOPMENT_ADMIN_CREATE_SUCCESS =
  "DEVELOPMENT_ADMIN_CREATE_SUCCESS";
export const DEVELOPMENT_ADMIN_CREATE_FAIL = "DEVELOPMENT_ADMIN_CREATE_FAIL";
export const DEVELOPMENT_ADMIN_CREATE_RESET = "DEVELOPMENT_ADMIN_CREATE_RESET";

export const DEVELOPMENT_ADMIN_UPDATE_REQUEST =
  "DEVELOPMENT_ADMIN_UPDATE_REQUEST";
export const DEVELOPMENT_ADMIN_UPDATE_SUCCESS =
  "DEVELOPMENT_ADMIN_UPDATE_SUCCESS";
export const DEVELOPMENT_ADMIN_UPDATE_FAIL = "DEVELOPMENT_ADMIN_UPDATE_FAIL";
export const DEVELOPMENT_ADMIN_UPDATE_RESET = "DEVELOPMENT_ADMIN_UPDATE_RESET";

export const DEVELOPMENT_ADMIN_DETAILS_REQUEST =
  "DEVELOPMENT_ADMIN_DETAILS_REQUEST";
export const DEVELOPMENT_ADMIN_DETAILS_SUCCESS =
  "DEVELOPMENT_ADMIN_DETAILS_SUCCESS";
export const DEVELOPMENT_ADMIN_DETAILS_FAIL = "DEVELOPMENT_ADMIN_DETAILS_FAIL";
export const DEVELOPMENT_ADMIN_DETAILS_RESET =
  "DEVELOPMENT_ADMIN_DETAILS_RESET";

export const DEVELOPMENT_ADMIN_DELETE_REQUEST =
  "DEVELOPMENT_ADMIN_DELETE_REQUEST";
export const DEVELOPMENT_ADMIN_DELETE_SUCCESS =
  "DEVELOPMENT_ADMIN_DELETE_SUCCESS";
export const DEVELOPMENT_ADMIN_DELETE_FAIL = "DEVELOPMENT_ADMIN_DELETE_FAIL";
export const DEVELOPMENT_ADMIN_DELETE_RESET = "DEVELOPMENT_ADMIN_DELETE_RESET";

export const DEVELOPMENT_LIST_REQUEST = "DEVELOPMENT_LIST_REQUEST";
export const DEVELOPMENT_LIST_SUCCESS = "DEVELOPMENT_LIST_SUCCESS";
export const DEVELOPMENT_LIST_FAIL = "DEVELOPMENT_LIST_FAIL";
export const DEVELOPMENT_LIST_RESET = "DEVELOPMENT_LIST_RESET";

export const DEVELOPMENT_DETAILS_REQUEST = "DEVELOPMENT_DETAILS_REQUEST";
export const DEVELOPMENT_DETAILS_SUCCESS = "DEVELOPMENT_DETAILS_SUCCESS";
export const DEVELOPMENT_DETAILS_FAIL = "DEVELOPMENT_DETAILS_FAIL";
export const DEVELOPMENT_DETAILS_RESET = "DEVELOPMENT_DETAILS_RESET";

export const DEVELOPMENT_SEARCH_REQUEST = "DEVELOPMENT_SEARCH_REQUEST";
export const DEVELOPMENT_SEARCH_SUCCESS = "DEVELOPMENT_SEARCH_SUCCESS";
export const DEVELOPMENT_SEARCH_FAIL = "DEVELOPMENT_SEARCH_FAIL";
export const DEVELOPMENT_SEARCH_RESET = "DEVELOPMENT_SEARCH_RESET";

export const DEVELOPMENT_LIMITS_REQUEST = "DEVELOPMENT_LIMITS_REQUEST";
export const DEVELOPMENT_LIMITS_SUCCESS = "DEVELOPMENT_LIMITS_SUCCESS";
export const DEVELOPMENT_LIMITS_FAIL = "DEVELOPMENT_LIMITS_FAIL";
export const DEVELOPMENT_LIMITS_RESET = "DEVELOPMENT_LIMITS_RESET";
