export const LOOKUP_ADMIN_LIST_REQUEST = "LOOKUP_ADMIN_LIST_REQUEST";
export const LOOKUP_ADMIN_LIST_SUCCESS = "LOOKUP_ADMIN_LIST_SUCCESS";
export const LOOKUP_ADMIN_LIST_FAIL = "LOOKUP_ADMIN_LIST_FAIL";
export const LOOKUP_ADMIN_LIST_RESET = "LOOKUP_ADMIN_LIST_RESET";

export const LOOKUP_ADMIN_GROUP_LIST_REQUEST =
  "LOOKUP_ADMIN_GROUP_LIST_REQUEST";
export const LOOKUP_ADMIN_GROUP_LIST_SUCCESS =
  "LOOKUP_ADMIN_GROUP_LIST_SUCCESS";
export const LOOKUP_ADMIN_GROUP_LIST_FAIL = "LOOKUP_ADMIN_GROUP_LIST_FAIL";
export const LOOKUP_ADMIN_GROUP_LIST_RESET = "LOOKUP_ADMIN_GROUP_LIST_RESET";

export const LOOKUP_ADMIN_CREATE_REQUEST = "LOOKUP_ADMIN_CREATE_REQUEST";
export const LOOKUP_ADMIN_CREATE_SUCCESS = "LOOKUP_ADMIN_CREATE_SUCCESS";
export const LOOKUP_ADMIN_CREATE_FAIL = "LOOKUP_ADMIN_CREATE_FAIL";
export const LOOKUP_ADMIN_CREATE_RESET = "LOOKUP_ADMIN_CREATE_RESET";

export const LOOKUP_ADMIN_UPDATE_REQUEST = "LOOKUP_ADMIN_UPDATE_REQUEST";
export const LOOKUP_ADMIN_UPDATE_SUCCESS = "LOOKUP_ADMIN_UPDATE_SUCCESS";
export const LOOKUP_ADMIN_UPDATE_FAIL = "LOOKUP_ADMIN_UPDATE_FAIL";
export const LOOKUP_ADMIN_UPDATE_RESET = "LOOKUP_ADMIN_UPDATE_RESET";

export const LOOKUP_ADMIN_DETAILS_REQUEST = "LOOKUP_ADMIN_DETAILS_REQUEST";
export const LOOKUP_ADMIN_DETAILS_SUCCESS = "LOOKUP_ADMIN_DETAILS_SUCCESS";
export const LOOKUP_ADMIN_DETAILS_FAIL = "LOOKUP_ADMIN_DETAILS_FAIL";
export const LOOKUP_ADMIN_DETAILS_RESET = "LOOKUP_ADMIN_DETAILS_RESET";

export const LOOKUP_ADMIN_DELETE_REQUEST = "LOOKUP_ADMIN_DELETE_REQUEST";
export const LOOKUP_ADMIN_DELETE_SUCCESS = "LOOKUP_ADMIN_DELETE_SUCCESS";
export const LOOKUP_ADMIN_DELETE_FAIL = "LOOKUP_ADMIN_DELETE_FAIL";
export const LOOKUP_ADMIN_DELETE_RESET = "LOOKUP_ADMIN_DELETE_RESET";

export const LOOKUP_LIST_REQUEST = "LOOKUP_LIST_REQUEST";
export const LOOKUP_LIST_SUCCESS = "LOOKUP_LIST_SUCCESS";
export const LOOKUP_LIST_FAIL = "LOOKUP_LIST_FAIL";
export const LOOKUP_LIST_RESET = "LOOKUP_LIST_RESET";
