export const MARKETPLACE_ADMIN_LIST_REQUEST = "MARKETPLACE_ADMIN_LIST_REQUEST";
export const MARKETPLACE_ADMIN_LIST_SUCCESS = "MARKETPLACE_ADMIN_LIST_SUCCESS";
export const MARKETPLACE_ADMIN_LIST_FAIL = "MARKETPLACE_ADMIN_LIST_FAIL";
export const MARKETPLACE_ADMIN_LIST_RESET = "MARKETPLACE_ADMIN_LIST_RESET";

export const MARKETPLACE_ADMIN_CREATE_REQUEST =
  "MARKETPLACE_ADMIN_CREATE_REQUEST";
export const MARKETPLACE_ADMIN_CREATE_SUCCESS =
  "MARKETPLACE_ADMIN_CREATE_SUCCESS";
export const MARKETPLACE_ADMIN_CREATE_FAIL = "MARKETPLACE_ADMIN_CREATE_FAIL";
export const MARKETPLACE_ADMIN_CREATE_RESET = "MARKETPLACE_ADMIN_CREATE_RESET";

export const MARKETPLACE_ADMIN_UPDATE_REQUEST =
  "MARKETPLACE_ADMIN_UPDATE_REQUEST";
export const MARKETPLACE_ADMIN_UPDATE_SUCCESS =
  "MARKETPLACE_ADMIN_UPDATE_SUCCESS";
export const MARKETPLACE_ADMIN_UPDATE_FAIL = "MARKETPLACE_ADMIN_UPDATE_FAIL";

export const MARKETPLACE_ADMIN_DETAILS_REQUEST =
  "MARKETPLACE_ADMIN_DETAILS_REQUEST";
export const MARKETPLACE_ADMIN_DETAILS_SUCCESS =
  "MARKETPLACE_ADMIN_DETAILS_SUCCESS";
export const MARKETPLACE_ADMIN_DETAILS_FAIL = "MARKETPLACE_ADMIN_DETAILS_FAIL";
export const MARKETPLACE_ADMIN_DETAILS_RESET =
  "MARKETPLACE_ADMIN_DETAILS_RESET";

export const MARKETPLACE_CREATE_REQUEST = "MARKETPLACE_CREATE_REQUEST";
export const MARKETPLACE_CREATE_SUCCESS = "MARKETPLACE_CREATE_SUCCESS";
export const MARKETPLACE_CREATE_FAIL = "MARKETPLACE_CREATE_FAIL";
export const MARKETPLACE_CREATE_RESET = "MARKETPLACE_CREATE_RESET";

export const MARKETPLACE_LIST_REQUEST = "MARKETPLACE_LIST_REQUEST";
export const MARKETPLACE_LIST_SUCCESS = "MARKETPLACE_LIST_SUCCESS";
export const MARKETPLACE_LIST_FAIL = "MARKETPLACE_LIST_FAIL";
export const MARKETPLACE_LIST_RESET = "MARKETPLACE_LIST_RESET";

export const MARKETPLACE_DETAILS_REQUEST = "MARKETPLACE_DETAILS_REQUEST";
export const MARKETPLACE_DETAILS_SUCCESS = "MARKETPLACE_DETAILS_SUCCESS";
export const MARKETPLACE_DETAILS_FAIL = "MARKETPLACE_DETAILS_FAIL";
export const MARKETPLACE_DETAILS_RESET = "MARKETPLACE_DETAILS_RESET";

export const MARKETPLACE_ADMIN_DELETE_REQUEST =
  "MARKETPLACE_ADMIN_DELETE_REQUEST";
export const MARKETPLACE_ADMIN_DELETE_SUCCESS =
  "MARKETPLACE_ADMIN_DELETE_SUCCESS";
export const MARKETPLACE_ADMIN_DELETE_FAIL = "MARKETPLACE_ADMIN_DELETE_FAIL";
export const MARKETPLACE_ADMIN_DELETE_RESET = "MARKETPLACE_ADMIN_DELETE_RESET";
