export const PARCEL_ADMIN_LIST_REQUEST = "PARCEL_ADMIN_LIST_REQUEST";
export const PARCEL_ADMIN_LIST_SUCCESS = "PARCEL_ADMIN_LIST_SUCCESS";
export const PARCEL_ADMIN_LIST_FAIL = "PARCEL_ADMIN_LIST_FAIL";
export const PARCEL_ADMIN_LIST_RESET = "PARCEL_ADMIN_LIST_RESET";

export const PARCEL_ADMIN_CREATE_REQUEST = "PARCEL_ADMIN_CREATE_REQUEST";
export const PARCEL_ADMIN_CREATE_SUCCESS = "PARCEL_ADMIN_CREATE_SUCCESS";
export const PARCEL_ADMIN_CREATE_FAIL = "PARCEL_ADMIN_CREATE_FAIL";
export const PARCEL_ADMIN_CREATE_RESET = "PARCEL_ADMIN_CREATE_RESET";

export const PARCEL_ADMIN_UPDATE_REQUEST = "PARCEL_ADMIN_UPDATE_REQUEST";
export const PARCEL_ADMIN_UPDATE_SUCCESS = "PARCEL_ADMIN_UPDATE_SUCCESS";
export const PARCEL_ADMIN_UPDATE_FAIL = "PARCEL_ADMIN_UPDATE_FAIL";
export const PARCEL_ADMIN_UPDATE_RESET = "PARCEL_ADMIN_UPDATE_RESET";

export const PARCEL_ADMIN_DETAILS_REQUEST = "PARCEL_ADMIN_DETAILS_REQUEST";
export const PARCEL_ADMIN_DETAILS_SUCCESS = "PARCEL_ADMIN_DETAILS_SUCCESS";
export const PARCEL_ADMIN_DETAILS_FAIL = "PARCEL_ADMIN_DETAILS_FAIL";
export const PARCEL_ADMIN_DETAILS_RESET = "PARCEL_ADMIN_DETAILS_RESET";

export const PARCEL_ADMIN_DELETE_REQUEST = "PARCEL_ADMIN_DELETE_REQUEST";
export const PARCEL_ADMIN_DELETE_SUCCESS = "PARCEL_ADMIN_DELETE_SUCCESS";
export const PARCEL_ADMIN_DELETE_FAIL = "PARCEL_ADMIN_DELETE_FAIL";
export const PARCEL_ADMIN_DELETE_RESET = "PARCEL_ADMIN_DELETE_RESET";

export const PARCEL_LIST_REQUEST = "PARCEL_LIST_REQUEST";
export const PARCEL_LIST_SUCCESS = "PARCEL_LIST_SUCCESS";
export const PARCEL_LIST_FAIL = "PARCEL_LIST_FAIL";
export const PARCEL_LIST_RESET = "PARCEL_LIST_RESET";
