export const PAYMENT_METHOD_ADMIN_LIST_REQUEST = "PAYMENT_METHOD_ADMIN_LIST_REQUEST";
export const PAYMENT_METHOD_ADMIN_LIST_SUCCESS = "PAYMENT_METHOD_ADMIN_LIST_SUCCESS";
export const PAYMENT_METHOD_ADMIN_LIST_FAIL = "PAYMENT_METHOD_ADMIN_LIST_FAIL";
export const PAYMENT_METHOD_ADMIN_LIST_RESET = "PAYMENT_METHOD_ADMIN_LIST_RESET";

export const PAYMENT_METHOD_ADMIN_CREATE_REQUEST = "PAYMENT_METHOD_ADMIN_CREATE_REQUEST";
export const PAYMENT_METHOD_ADMIN_CREATE_SUCCESS = "PAYMENT_METHOD_ADMIN_CREATE_SUCCESS";
export const PAYMENT_METHOD_ADMIN_CREATE_FAIL = "PAYMENT_METHOD_ADMIN_CREATE_FAIL";
export const PAYMENT_METHOD_ADMIN_CREATE_RESET = "PAYMENT_METHOD_ADMIN_CREATE_RESET";

export const PAYMENT_METHOD_ADMIN_UPDATE_REQUEST = "PAYMENT_METHOD_ADMIN_UPDATE_REQUEST";
export const PAYMENT_METHOD_ADMIN_UPDATE_SUCCESS = "PAYMENT_METHOD_ADMIN_UPDATE_SUCCESS";
export const PAYMENT_METHOD_ADMIN_UPDATE_FAIL = "PAYMENT_METHOD_ADMIN_UPDATE_FAIL";
export const PAYMENT_METHOD_ADMIN_UPDATE_RESET = "PAYMENT_METHOD_ADMIN_UPDATE_RESET";

export const PAYMENT_METHOD_ADMIN_DETAILS_REQUEST = "PAYMENT_METHOD_ADMIN_DETAILS_REQUEST";
export const PAYMENT_METHOD_ADMIN_DETAILS_SUCCESS = "PAYMENT_METHOD_ADMIN_DETAILS_SUCCESS";
export const PAYMENT_METHOD_ADMIN_DETAILS_FAIL = "PAYMENT_METHOD_ADMIN_DETAILS_FAIL";
export const PAYMENT_METHOD_ADMIN_DETAILS_RESET = "PAYMENT_METHOD_ADMIN_DETAILS_RESET";

export const PAYMENT_METHOD_ADMIN_DELETE_REQUEST = "PAYMENT_METHOD_ADMIN_DELETE_REQUEST";
export const PAYMENT_METHOD_ADMIN_DELETE_SUCCESS = "PAYMENT_METHOD_ADMIN_DELETE_SUCCESS";
export const PAYMENT_METHOD_ADMIN_DELETE_FAIL = "PAYMENT_METHOD_ADMIN_DELETE_FAIL";
export const PAYMENT_METHOD_ADMIN_DELETE_RESET = "PAYMENT_METHOD_ADMIN_DELETE_RESET";

export const PAYMENT_METHOD_LIST_REQUEST = "PAYMENT_METHOD_LIST_REQUEST";
export const PAYMENT_METHOD_LIST_SUCCESS = "PAYMENT_METHOD_LIST_SUCCESS";
export const PAYMENT_METHOD_LIST_FAIL = "PAYMENT_METHOD_LIST_FAIL";
export const PAYMENT_METHOD_LIST_RESET = "PAYMENT_METHOD_LIST_RESET";

export const PAYMENT_METHOD_DETAILS_REQUEST = "PAYMENT_METHOD_DETAILS_REQUEST";
export const PAYMENT_METHOD_DETAILS_SUCCESS = "PAYMENT_METHOD_DETAILS_SUCCESS";
export const PAYMENT_METHOD_DETAILS_FAIL = "PAYMENT_METHOD_DETAILS_FAIL";
export const PAYMENT_METHOD_DETAILS_RESET = "PAYMENT_METHOD_DETAILS_RESET";

export const PAYMENT_METHOD_SEARCH_REQUEST = "PAYMENT_METHOD_SEARCH_REQUEST";
export const PAYMENT_METHOD_SEARCH_SUCCESS = "PAYMENT_METHOD_SEARCH_SUCCESS";
export const PAYMENT_METHOD_SEARCH_FAIL = "PAYMENT_METHOD_SEARCH_FAIL";
export const PAYMENT_METHOD_SEARCH_RESET = "PAYMENT_METHOD_SEARCH_RESET";

export const PAYMENT_METHOD_LIMITS_REQUEST = "PAYMENT_METHOD_LIMITS_REQUEST";
export const PAYMENT_METHOD_LIMITS_SUCCESS = "PAYMENT_METHOD_LIMITS_SUCCESS";
export const PAYMENT_METHOD_LIMITS_FAIL = "PAYMENT_METHOD_LIMITS_FAIL";
export const PAYMENT_METHOD_LIMITS_RESET = "PAYMENT_METHOD_LIMITS_RESET";