export const PRODUCT_ADMIN_LIST_REQUEST = "PRODUCT_ADMIN_LIST_REQUEST";
export const PRODUCT_ADMIN_LIST_SUCCESS = "PRODUCT_ADMIN_LIST_SUCCESS";
export const PRODUCT_ADMIN_LIST_FAIL = "PRODUCT_ADMIN_LIST_FAIL";
export const PRODUCT_ADMIN_LIST_RESET = "PRODUCT_ADMIN_LIST_RESET";

export const PRODUCT_ADMIN_CREATE_REQUEST = "PRODUCT_ADMIN_CREATE_REQUEST";
export const PRODUCT_ADMIN_CREATE_SUCCESS = "PRODUCT_ADMIN_CREATE_SUCCESS";
export const PRODUCT_ADMIN_CREATE_FAIL = "PRODUCT_ADMIN_CREATE_FAIL";
export const PRODUCT_ADMIN_CREATE_RESET = "PRODUCT_ADMIN_CREATE_RESET";

export const PRODUCT_ADMIN_UPDATE_REQUEST = "PRODUCT_ADMIN_UPDATE_REQUEST";
export const PRODUCT_ADMIN_UPDATE_SUCCESS = "PRODUCT_ADMIN_UPDATE_SUCCESS";
export const PRODUCT_ADMIN_UPDATE_FAIL = "PRODUCT_ADMIN_UPDATE_FAIL";

export const PRODUCT_ADMIN_DETAILS_REQUEST = "PRODUCT_ADMIN_DETAILS_REQUEST";
export const PRODUCT_ADMIN_DETAILS_SUCCESS = "PRODUCT_ADMIN_DETAILS_SUCCESS";
export const PRODUCT_ADMIN_DETAILS_FAIL = "PRODUCT_ADMIN_DETAILS_FAIL";
export const PRODUCT_ADMIN_DETAILS_RESET = "PRODUCT_ADMIN_DETAILS_RESET";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_RESET = "PRODUCT_LIST_RESET";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";

export const PRODUCT_CART_REQUEST = "PRODUCT_CART_REQUEST";
export const PRODUCT_CART_SUCCESS = "PRODUCT_CART_SUCCESS";
export const PRODUCT_CART_FAIL = "PRODUCT_CART_FAIL";
export const PRODUCT_CART_RESET = "PRODUCT_CART_RESET";

export const PRODUCT_ADMIN_DELETE_REQUEST = "PRODUCT_ADMIN_DELETE_REQUEST";
export const PRODUCT_ADMIN_DELETE_SUCCESS = "PRODUCT_ADMIN_DELETE_SUCCESS";
export const PRODUCT_ADMIN_DELETE_FAIL = "PRODUCT_ADMIN_DELETE_FAIL";
export const PRODUCT_ADMIN_DELETE_RESET = "PRODUCT_ADMIN_DELETE_RESET";

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL";
export const PRODUCT_SEARCH_RESET = "PRODUCT_SEARCH_RESET";
