export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_VERIFICATION_STATUS_REQUEST = "USER_VERIFICATION_STATUS_REQUEST"
export const USER_VERIFICATION_STATUS_SUCCESS = "USER_VERIFICATION_STATUS_SUCCESS"
export const USER_VERIFICATION_STATUS_FAIL = "USER_VERIFICATION_STATUS_FAIL"

export const USER_VERIFICATION_REQUEST = "USER_VERIFICATION_REQUEST"
export const USER_VERIFICATION_SUCCESS = "USER_VERIFICATION_SUCCESS"
export const USER_VERIFICATION_FAIL = "USER_VERIFICATION_FAIL"

export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST"
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS"
export const USER_FORGOT_PASSWORD_FAIL = "USER_FORGOT_PASSWORD_FAIL"

export const USER_FORGOT_STATUS_REQUEST = "USER_FORGOT_STATUS_REQUEST";
export const USER_FORGOT_STATUS_SUCCESS = "USER_FORGOT_STATUS_SUCCESS";
export const USER_FORGOT_STATUS_FAIL = "USER_FORGOT_STATUS_FAIL";

export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST";
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL"

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST"
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS"
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL"
export const USER_PROFILE_UPDATE_RESET = "USER_PROFILE_UPDATE_RESET"

export const USER_ARTIST_TYPE_REQUEST = "USER_ARTIST_TYPE_REQUEST"
export const USER_ARTIST_TYPE_SUCCESS = "USER_ARTIST_TYPE_SUCCESS"
export const USER_ARTIST_TYPE_FAIL = "USER_ARTIST_TYPE_FAIL"

export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAIL = "USER_LIST_FAIL"
export const USER_LIST_RESET = "USER_LIST_RESET"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_ADMIN_UPDATE_REQUEST = "USER_ADMIN_UPDATE_REQUEST";
export const USER_ADMIN_UPDATE_SUCCESS = "USER_ADMIN_UPDATE_SUCCESS";
export const USER_ADMIN_UPDATE_FAIL = "USER_ADMIN_UPDATE_FAIL";
export const USER_ADMIN_UPDATE_RESET = "USER_ADMIN_UPDATE_RESET";

export const USER_ADMIN_REGISTER_REQUEST = "USER_ADMIN_REGISTER_REQUEST";
export const USER_ADMIN_REGISTER_SUCCESS = "USER_ADMIN_REGISTER_SUCCESS";
export const USER_ADMIN_REGISTER_FAIL = "USER_ADMIN_REGISTER_FAIL";